@startuml usecase api

scale 1
left to right direction

actor client
actor client2

rectangle "Automation Core" {
    (Selenium)-> (Cucumber): include
    (Selenium) -> (Api)
    client -> (Api)
}

@enduml


