@startuml

' Object <|-- ArrayList
' ArrayList : equals()
' ArrayList : Object[] elementData
' ArrayList : size()

package org.openqa.selenium #DDDDDD {
  SearchContext <|-- WebDriver
  SearchContext <|-- WebElement
  TakesScreenshot <|-- WebElement

  interface WebDriver {
    +getTitle():String
  }

  interface SearchContext {
    +findElement(by:By):WebElement
    +findElements(by:By):List<WebElement>
  }

  abstract class By {
    +{static} id(id:String):By
    +{static} name(name:String):By
    +{static} tagName(tagName:String):By
    +{static} className(className:String):By
    +{static} cssSelector(cssSelector:String):By
    +findElement(context:SearchContext):WebElement
    +findElements(context:SearchContext):List<WebElement>
    +{abstract} findElements(context:SearchContext):List<WebElement>
  }

  interface WebElement {
    +click():void
    +submit():void
    +sendKeys(keysToSend: CharSequence...):void
    +clear():void
    +getTagName():String
    +getAttribute(name: String):String
    +isSelected():boolean
    +isEnabled():boolean
    +getText():String
    +findElements(by: By):List<WebElement>
    +findElement(by: By):WebElement
    +isDisplayed():boolean
    +getLocation():Point
    +getSize():Dimension
    +getRect():Rectangle
    +getCssValue(propertyName:String):String
  }

  interface TakesScreenshot  {
    +getScreenshotAs(target:OutputType<X>):<X> X
  }
}

package com.indra.product.automation.core.webcommand #DDDDDD {
  WebDriver ..> BasicCommand
  class BasicCommand {
    -driver:Driver
    +BasicCommand(driver:WebDriver)
    +getTitle():String
    +encontra(name:String):WebElement
    +mudarAba(numero:int):void
    +trocarJanela(elemento:String):void 
    +encontra(name:String):WebElement
    +elementoExiste(elemento: String):void
    +elementoEstaHabilitado(elemento:String):void
    +esperarElemento(elemento:String, time:int):void 
    +escrever(elemento:String, texto:String):void
  }
}

package com.indra.product.automation.core.page #8080ff {
  BasicCommand <|-- GitlabPage
  class GitlabPage {
    +GitlabPage(driver:WebDriver)
  }
}

package com.indra.product.automation.core.steps #ff8040 {
  WebDriver ..> GitlabSteps
  GitlabPage ..> GitlabSteps
  class GitlabSteps {

  }
}




@enduml
